name: weight_tracker
description: Flutter App Development for Demo Purpose
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0
  flutter_svg: 2.0.6
  shared_preferences: 2.1.1
  dio: 5.2.1+1
  go_router: ^12.0.0
  amplify_flutter: ^1.5.0
  amplify_datastore: ^1.5.0
  amplify_auth_cognito: ^1.5.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  logger: ^1.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher-playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/ic_launcher-playstore.png"

flutter:
  assets:
    - assets/.
    - assets/environments/.
    - assets/icons/.
    - assets/images/.
    - assets/fonts/.
  uses-material-design: true
  generate: true
